[mypy]
python_version = 3.13
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = False
warn_no_return = True
warn_unreachable = True
strict_equality = True

# Allow imports from third-party packages without type stubs
disable_error_code = import-untyped

[mypy-apscheduler.*]
ignore_missing_imports = True

[mypy-speedtest.*]
ignore_missing_imports = True
ignore_errors = True
