sonar.projectKey=Hermes
sonar.projectName=Hermes
sonar.host.url=https://sonarqube.greenflametech.net
sonar.sources=src,frontend/src
sonar.tests=tests
sonar.test.inclusions=frontend/src/test/**
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.python.bandit.reportPaths=bandit-report.json
sonar.python.mypy.reportPaths=mypy-report.txt
sonar.externalIssuesReportPaths=sonar-vulture.json,sonar-radon.json,sonar-semgrep.json
sonar.exclusions=\
  **/__pycache__/**,\
  **/.venv/**,\
  **/logs/**,\
  **/*.pyc,\
  **/node_modules/**,\
  **/dist/**,\
  docker-compose.yml

sonar.coverage.exclusions=\
  frontend/src/**

sonar.security.hotspot.exclusions=\
  tests/**